# requirements.yml
collections:
  - name: ansible.utils
    version: 2.11.0
  - name: ansible.netcommon
    version: 5.3.0
  - name: cisco.nxos
    version: 5.3.0
  - name: https://github.com/CiscoDevNet/ansible-dcnm.git
    type: git
    version: netascode_changes_vpc_fabric
  # - name: https://github.com/netascode/ansible-dc-vxlan.git
  #   type: git
  #   version: develop   # change version later
