---
vxlan:
  policy:
    policies:
      - name: grpc feature
        template_name: switch_freeform
        filename: /Users/devegupt/workspace/sac-ndfc/nac-ndfc/host_vars/grpc_feature.yaml
      - name: grpc config
        template_name: switch_freeform
        template_vars:
          CONF: |-
            grpc port 50051
            grpc use-vrf default
            grpc gnmi max-concurrent-call 16
      - name: alias cfg  # description
        filename: /Users/devegupt/workspace/sac-ndfc/nac-ndfc/host_vars/copy_netascode4_vrf_lite_ebgp/alias.cfg
      - name: banner config  # description
        template_name: banner
        template_vars:
          BANNER: "VXLAN as Code Banner"
          BANNERDELIMITER: "_"
          TYPE: "motd"
    groups:
      - name: server leafs
        priority: 500
        policies:
          - name: grpc feature
            priority: 50
          - name: grpc config
          - name: banner config
          - name: alias cfg
    switches:
      - name: netascode4-ebgp-bl1
        groups:
          - server leafs
      - name: netascode4-ebgp-bl2
        groups:
          - server leafs